###
#
##

language: bash

install: true

before_deploy:
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && export MESSAGE="pull request" || export MESSAGE="not pull request"'
# before_deploy

deploy:
  provider: script
  script:
    - echo $MESSAGE
  on:
    repo: mcarey-solstice/playground
    all_branches: true
# deploy

after_deploy:
  - echo "After the deployment"
# after_deploy

# .travis.yml
